name: Bulid Webdollar Miner Container

on:
  push:
    branches:
      - 'master'
  schedule:
    - cron: "0 2 * * SUN"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls -lah
      - run: ./docker-build.sh
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
