name: Bulid Webdollar Miner Container

on:
  push:
    branches:
      - 'master'
# TODO: On cron weekly?
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - run: ls -lah
      - run: ./docker-build.sh
        env:
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
